# Generated by Django 5.0.1 on 2024-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(default="", max_length=300),
        ),
    ]
