# Generated by Django 5.0.1 on 2024-01-17 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_transaction_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amounr",
            new_name="amount",
        ),
    ]
