# Generated by Django 5.0.1 on 2024-01-18 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_rename_amounr_transaction_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="is_expance",
            new_name="is_expanse",
        ),
    ]
