# Generated by Django 5.0.1 on 2024-01-24 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0008_budget_shared_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="shared_to",
        ),
        migrations.AddField(
            model_name="budget",
            name="shared_to",
            field=models.ManyToManyField(
                blank=True, related_name="shared_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
