# Generated by Django 5.0.1 on 2024-01-25 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0010_alter_budget_shared_to_alter_budget_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
