# Generated by Django 5.0.1 on 2024-01-25 13:06

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    BudgetModel = apps.get_model("budget", "budget")
    TransactionModel = apps.get_model("budget", "transaction")

    for row in BudgetModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save(update_fields=["unique_id"])

    for row in TransactionModel.objects.all():
        row.unique_id = uuid.uuid4()
        row.save(update_fields=["unique_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0011_budget_unique_id_transaction_unique_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
