# Generated by Django 5.0.1 on 2024-01-25 13:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0012_populate_uuid_20240125_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="unique_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
