# Generated by Django 5.0.1 on 2024-01-25 15:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0013_remove_uuid_null_20240125_1306"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 25, 15, 50, 8, 884394, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 27, 15, 50, 8, 884394, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="budget.budget",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
