# Generated by Django 5.0.1 on 2024-01-25 15:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0014_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="users",
        ),
        migrations.AddField(
            model_name="invitation",
            name="from_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="from_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="to_users",
            field=models.ManyToManyField(
                related_name="to_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 15, 51, 49, 689659, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 27, 15, 51, 49, 689659, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
