# Generated by Django 5.0.1 on 2024-01-25 15:57

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0015_remove_invitation_users_invitation_from_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="shared_to",
            field=models.ManyToManyField(
                blank=True, related_name="shared_to", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 15, 57, 3, 15560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 27, 15, 57, 3, 15560, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
