# Generated by Django 5.0.1 on 2024-01-25 19:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0016_alter_budget_shared_to_alter_invitation_valid_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitation",
            name="to_users",
        ),
        migrations.AddField(
            model_name="invitation",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitation",
            name="to_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="to_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 25, 19, 19, 11, 923688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 27, 19, 19, 11, 923688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
