# Generated by Django 5.0.1 on 2024-02-06 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0017_remove_invitation_to_users_invitation_accepted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="valid_from",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="valid_to",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=300)),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="category",
                        related_query_name="category",
                        to="budget.transaction",
                    ),
                ),
            ],
        ),
    ]
