# Generated by Django 5.0.1 on 2024-02-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0018_alter_invitation_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="category",
                to="budget.transaction",
            ),
        ),
    ]
