# Generated by Django 5.0.1 on 2024-02-06 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_alter_transactioncategory_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactioncategory",
            name="transaction",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="budget.transactioncategory",
            ),
        ),
    ]
