# Generated by Django 5.0.1 on 2024-02-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0021_remove_transaction_is_expense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioncategory",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
