name: tests
run-name: Run unit tests
on:
  pull_request:
    branches:
      - main
jobs: 
  run-go-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
        cache-dependency-path: subdir/go.sum
    - name: Install dependencies
      run: |
          go mod download

    - name: Run Go Tests
      run: make tests
